language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements/tests.txt --use-mirrors
  - pip install -r requirements/package.txt --use-mirrors
before_script:
  - flake8 antigate
script:
  - coverage run --branch --source=antigate test_cases.py
  - coverage report --omit="test*"
branches:
  only:
    - master
    - development
after_success: coveralls
